#server:
#  port: 8089
spring:
  #Redis配置
  redis:
    database: 0
    host: 192.168.140.120
    port: 19000
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 1000
        min-idle: 5
        timeout: 0