server:
  port: 8082 #服务端口

spring:
  application:
    name: springcloud-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/hqz010/springcloud-framework/tree/master/springcloud-config/src/main/resources/config #具体的配置文件的git地址
          #username:
          #password:
  kafka:
  #rabbitmq: #RabbitMQ相关的配置
    host: 192.168.140.121
    port: 9095
    #username: guest
    #password: guest

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://cloud:cloud@localhost:8081/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: localhost

management:
  security:
    enabled: false #是否开启actuator安全认证
