eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://cloud:cloud@127.0.0.1:8081/eureka/

spring:
  cloud:
    config:
      name: microservice #对应的配置服务中的应用名称
      profile: dev #对应配置服务中的{profile}
      label: master #对应的分支
      discovery:
        enabled: true #启用发现服务功能
        service-id: microservice-config-server #指定服务名称
  spring:
  application:
    name: itcasst-microservice-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: http://172.16.55.138:10080/zhangzhijun/itcast-config-server.git
          #username: zhangzhijun
          #password: 123456
  rabbitmq: #RabbitMQ相关的配置
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
